
SYMBOL = "symbol"

#============ Time ============#
YEAR = "year"
PERIOD = "period"
FREQ = "freq"

#============ Balance Sheet Metrics ============#
ACCOUTNS_PAYABLE = "accountsPayable"
ACCOUNTS_RECEIVABLES = "accountsReceivables"
ACCRUED_LIABILITY = "accruedLiability"
ACCUMULATED_DEPRECIATION = "accumulatedDepreciation"
CASH_EQUIVALENTS = "cashEquivalents"
CASH_SHORT_TERM_INVESTMENTS = "cashShortTermInvestments"
COMMON_STOCK = "commonStock"
CURRENT_ASSETS = "currentAssets"
CURRENT_LIABILITIES = "currentLiabilities"
CURRENT_PORTION_LONG_TERM_DEBT = "currentPortionLongTermDebt"
DEFERRED_INCOME_TAX = "deferredIncomeTax"
GOODWILL = "goodwill"
INTANGIBLES_ASSETS = "intangiblesAssets"
INVENTORY = "inventory"
LIABILITIES_SHAREHOLDERS_EQUITY = "liabilitiesShareholdersEquity"
LONG_TERM_DEBT = "longTermDebt"
LONG_TERM_INVESTMENTS = "longTermInvestments"
OTHER_CURRENT_ASSETS = "otherCurrentAssets"
OTHER_CURRENT_LIABILITIES = "otherCurrentliabilities"
OTHER_EQUITY = "otherEquity"
OTHER_LIABILITIES = "otherLiabilities"
OTHER_LONG_TERM_ASSETS = "otherLongTermAssets"
OTHER_RECEIVABLES = "otherReceivables"
PERIOD = "period"
PROPERTY_PLANT_EQUIPMENT = "propertyPlantEquipment"
RETAINED_EARNINGS = "retainedEarnings"
SHARES_OUTSTANDING = "sharesOutstanding"
SHORT_TERM_DEBT = "shortTermDebt"
SHORT_TERM_INVESTMENTS = "shortTermInvestments"
TANGIBLE_BOOK_VALUE_PERSHARE = "tangibleBookValueperShare"
TOTAL_ASSETS = "totalAssets"
TOTAL_DEBT = "totalDebt"
TOTAL_EQUITY = "totalEquity"
TOTAL_LIABILITIES = "totalLiabilities"
TOTAL_LONG_TERM_DEBT = "totalLongTermDebt"
TOTAL_RECEIVABLES = "totalReceivables"
TREASURY_STOCK = "treasuryStock"


#============ Income Statement Metrics ============#
COST_OF_GOODS_SOLD = 'costOfGoodsSold'
DILUTED_AVERAGE_SHARES_OUTSTANDING = 'dilutedAverageSharesOutstanding'
DILUTED_EPS = 'dilutedEPS'
EBIT = 'ebit'
GROSS_INCOME = "grossIncome"
INTEREST_INCOME_EXPENSE = "interestIncomeExpense"
NET_INCOME = "netIncome"
NET_INCOME_AFTER_TAXES = "netIncomeAfterTaxes"
PERIOD = "period"
PRETAX_INCOME = "pretaxIncome"
PROVISION_FOR_INCOME_TAXES = "provisionforIncomeTaxes"
RESEARCH_DEVELOPMENT = "researchDevelopment"
REVENUE = "revenue"
SGA_EXPENSE = "sgaExpense"
TOTAL_OPERATING_EXPENSE = "totalOperatingExpense"
TOTAL_OTHER_INCOME_EXPENSE_NET = "totalOtherIncomeExpenseNet"

#============ Cash Flow Statement Metrics ============#
CAPEX = "capex"
CASH_DIVIDENDS_PAID = "cashDividendsPaid"
CASH_INTEREST_PAID = "cashInterestPaid"
CASH_TAXES_PAID = "cashTaxesPaid"
CHANGE_IN_CASH = "changeinCash"
CHANGES_IN_WORKING_CAPITAL = "changesinWorkingCapital"
DEFERRED_TAXES_INVESTMENT_TAX_CREDIT = "deferredTaxesInvestmentTaxCredit"
DEPRECIATION_AMORTIZATION = "depreciationAmortization"
FOREIGN_EXCHANGE_EFFECTS = "foreignExchangeEffects"
ISSUANCE_REDUCTION_CAPITAL_STOCK = "issuanceReductionCapitalStock"
ISSUANCE_REDUCTION_DEBT_NET = "issuanceReductionDebtNet"
NET_CASH_FINANCING_ACTIVITIES = "netCashFinancingActivities"
NET_INCOME_STARTING_LINE = "netIncomeStartingLine"
NET_INVESTING_CASH_FLOW = "netInvestingCashFlow"
NET_OPERATING_CASH_FLOW = "netOperatingCashFlow"
OTHER_FUNDS_FINANCING_ITEMS = "otherFundsFinancingItems"
OTHER_FUNDS_NON_CASH_ITEMS = "otherFundsNonCashItems"
OTHER_INVESTING_CASH_FLOW_ITEMS_TOTAL = "otherInvestingCashFlowItemsTotal"

#============ Revenue Estimates ============#
NUMBER_ANALYSTS = "numberAnalysts"
PERIOD = "period"
REVENUE_AVG = "revenueAvg"
REVENUE_HIGH = "revenueHigh"
REVENUE_LOW = "revenueLow"


#============ Basic Financials ============#
PE_BASIC_EXCL_EXTRA_TTM = "peBasicExclExtraTTM"
PE_EXCL_EXTRA_ANNUAL = "peExclExtraAnnual"
PE_EXCL_EXTRA_HIGH_TTM = "peExclExtraHighTTM"
PE_EXCL_EXTRA_TTM = "peExclExtraTTM"
PE_EXCL_LOW_TTM = "peExclLowTTM"
PE_INCL_EXTRA_TTM = "peInclExtraTTM"
PE_NORMALIZED_ANNUAL = "peNormalizedAnnual"